# Generated by Django 5.1.1 on 2024-10-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
    ]
