# Generated by Django 5.1.1 on 2024-10-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_card_checklist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlist',
            name='max_cards',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
