# Generated by Django 5.1.1 on 2024-10-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_cardlist_max_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlist',
            name='amount_cards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
