# Generated by Django 5.1.2 on 2024-12-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_tag_alter_cardlist_amount_cards_card_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlist',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
