# Generated by Django 5.1.2 on 2024-12-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_cardlist_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardlist',
            name='position',
        ),
    ]
